[build]
  publish = "public"
  functions = "netlify/functions"

[dev]
  publish = "public"
  functions = "netlify/functions"
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
[build.environment]
  # This is just a placeholder. The actual environment variable will be set in the Netlify dashboard
  # PASSWORD_LINKS_JSON = '[{"pwd": "example", "link": "https://zoom.us/example"}]'
